RegisterServerEvent("esx_ava_personalmenu:kick")
AddEventHandler("esx_ava_personalmenu:kick", function(author, id, label)
	DropPlayer(id, "Tu as été kick par "..author.." : ".. label)
end)

TriggerEvent('es:addGroupCommand', 'a', 'admin', function(source, args, user)
	TriggerClientEvent('esx_ava_personalmenu:toggle_admin_mode', source)
end, function(source, args, user)
	TriggerClientEvent('chat:addMessage', source, { args = { '^1SYSTEM', 'Insufficient Permissions.' } })
end, {help = "Toggle admin mode", params = {}})
