RegisterServerEvent('cmg1_animations:sync')
AddEventHandler('cmg1_animations:sync', function(target, animationLib,animationLib2, animation, animation2, distans, distans2, height,targetSrc,length,spin,controlFlagSrc,controlFlagTarget,animFlagTarget)
	--print("got to srv cmg1_animations:sync")
	TriggerClientEvent('cmg1_animations:syncTarget', targetSrc, source, animationLib2, animation2, distans, distans2, height, length,spin,controlFlagTarget,animFlagTarget)
	--print("triggering to target: " .. tostring(targetSrc))
	TriggerClientEvent('cmg1_animations:syncMe', source, animationLib, animation,length,controlFlagSrc,animFlagTarget)
end)

RegisterServerEvent('cmg1_animations:stop')
AddEventHandler('cmg1_animations:stop', function(targetSrc)
	TriggerClientEvent('cmg1_animations:cl_stop', targetSrc)
end)